### ISSUE TITLE
fails to compile: slingstart needs mom and jms jars

### ISSUE THREAD

**Issue by cons0l3** [bdelacretaz/sling-adaptto-2016#3]
Hi, 

found your talk through adaptto-2016 conference pages and got interested.

I use the newest sling svn snapshot (2016-10-20) and followed the steps in your readme.

When I compile mvn clean install, I fail to compile the default-processor:

> [ERROR] Failed to execute goal on project default-processor: Could not resolve dependencies for project ch.x42.at16:default-processor:slingstart:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.apache.sling:org.apache.sling.jms:jar:0.0.1-SNAPSHOT, org.apache.sling:org.apache.sling.mom:jar:0.0.1-SNAPSHOT: Could not find artifact org.apache.sling:org.apache.sling.jms:jar:0.0.1-SNAPSHOT -> [Help 1]

I have compiled/installed "contrib/common/mom" and "samples/slingshot" by
sling.svn/contrib/common/mom > mvn install
sling.svn/samples/slingshot >  mvn install

I have also compiled/installed tooling/maven/slingstart-maven-plugin

Hints on what I am doing wrong?

Cheers
Carsten

**Comment by bdelacretaz** [comment]
Commit 0c85ca7 should fix this - these modules have been released in the meantime, we don't need the snapshots anymore.

**Comment by cons0l3** [comment]
fixed.

super! thx. 

I was looking in all the pom to find the dependency, but obviously have not understood - and still don't - where the  provisioning/ comes into play.

I am new to sling-world and try out every samples ;-)

**Comment by bdelacretaz** [comment]
> I am new to sling-world and try out every samples 

Great! Hope you like this one ;-)
